name: "ZAP API Scan"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Guardian Care Store
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: develop

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-weekly'
          format: openapi
          #this target url should be localhost to get a correct output, im confused tbh
          target: 'https://preview.owasp-juice.shop/swagger.yml'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'